services:
  - type: web
    name: qr-menu
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true 